logging:
  level:
    root: INFO
    pe.bancom: TRACE
    org.springframework: INFO
    com.microsoft: ERROR

server:
  port: 8080
  servlet:
    context-path: /bancom/support/v1.0

spring:
  application:
    name: bancom--app
  jackson:
    time-zone: America/Lima
    locale: es_PE
  flyway:
    enabled: true
    url: jdbc:mysql://localhost:3306/bancom
    user: root
    password: "@P4ssw0rD"
    baseline-on-migrate: true
  jpa:
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    open-in-view: false

pe.bancom:
  database:
    url: jdbc:mysql://localhost:3306/bancom?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: "@P4ssw0rD"
    driverClassName: com.mysql.cj.jdbc.Driver