logging:
  level:
    root: INFO
    pe.bancom: TRACE
    org.springframework: INFO
    com.microsoft: ERROR
    springfox.documentation: TRACE

server:
  port: 8080
  servlet:
    context-path: /support/v1.0

spring:
  application:
    name: bancom--app
  jackson:
    time-zone: America/Lima
    locale: es_PE
  flyway:
    enabled: true
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/bancom
    user: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    baseline-on-migrate: true
  jpa:
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

pe.bancom:
  api:
    path: bancom
  database:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/bancom?allowPublicKeyRetrieval=true&useSSL=false
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver