version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_bancom
    environment:
      MYSQL_ROOT_PASSWORD: "@P4ssw0rD"
      MYSQL_DATABASE: bancom
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: